src/components/ComponentTabs.tsx, src/design-system/components/tabs/index.tsx
This PR makes tabs navigation rely on the `/path` instead of the `/path#hash?search`. We only use it with paths at the moment and having it rely on hash and search makes using hash and search for other purposes impossible.
This is a breaking change and will require refactoring once the dep is updated.
Everything should continue to work.
positions
=> fix(tabs): tabs navigation should rely only on the path

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, src/design-system/components/tabs/index.tsx
This PR makes tabs prerenderable
N/A
Manual validation in storybook
positions
=> fix(Tabs): make Tabs prerenderable

src/design-system/components/snackbar-provider/index.tsx
Update to snackbar word-break property to avoid unnecessary splitting of words in snackbar elements- still allows breaking of single words that would exceed container width (e.g. super long filenames)
Before:
After:
N/A
positions
=> fix(ui): update word break rules for snackbar

src/design-system/components/tabs/index.spec.tsx, src/design-system/components/tabs/index.tsx
This PR fixes inactive tab prerendering issues in the `Tabs` component.
N/A
Manual validation + autotests.
positions
=> fix(ui): ensure that prerendered tabs have a size offscreen

src/design-system/components/text-field/index.tsx
Cleans up CSS props to not include `--moz` and `--webkit` CSS props.
No.
positions
=> fix: remove kebab props from MUI components

src/design-system/components/dialog/Dialog.tsx, src/design-system/components/dialog/DialogFormActions.tsx, src/design-system/components/dialog/dialog.stories.tsx
Add appropriate color vars for dark theme modals to ensure readable contrast.
Some values are hardcoded/overridden and will need to be addressed on a case-by-case basis.
positions
=> dark theme update for forms/modal content

README.md, src/design-system/components/tooltip/index.tsx
Tooltip delay was too slow (1.5s) updated to 200ms, fixed broken storybook url in readme
None.
N/A
positions
=> fix(ui): update tooltip default delay & storybook url fix

src/design-system/components/dialog/Dialog.tsx, src/design-system/components/select/index.tsx, src/design-system/theme/components/pagination.ts, src/design-system/theme/components/tabs.ts, src/design-system/theme/paletteDark.ts
Modal scrollbars:
Dark mode tabs:
* update tooltip backgrounds for offset/contrast, remove opacity
* update pagination for consistency with platform patterns
* update tabs for consistency with platform patterns
* add scrollbar styles for dialog/modal components
* add contrast background to dark palette
N/A
positions
=> feature(ui): dark mode cleanup & palette updates

src/design-system/theme/typography.ts
Revert Chris' body font size updates
from:
to:
n/a
positions
=> fix(ui): revert font size updates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, src/design-system/theme/palette.ts, src/design-system/theme/paletteDark.ts
Lightens secondary text color for better distinction vs primary.
n/a
n/a
positions
=> fix(ui): lighten secondary text

src/design-system/components/dialog/DialogTitle.tsx
This PR allows titles dialog titles and makes sure that the x icon isn't being misplaced when there is no title.
N/A
positions
=> feat(ui): allow title-less dialog titles

src/design-system/components/table/index.tsx, src/design-system/components/table/table.stories.tsx
Adds a prop to the `<Table>` component for sticky headers.
In order for `position: sticky` to function properly an explicit height must be set for the parent container (`height: 100%` is acceptable and applied to the wrapping `<Box>` component to assist here).
n/a
positions
=> feat(ui): add sticky prop for sticky table headers

src/design-system/components/text-field/index.tsx
This PR disables autocomplete in dashlane and LastPass if `autoComplete=off` or `autoComplete=nope`.
N/A
positions
=> feat(TextField): disable autocomplete in dashlane and lastpass if `autocomplete` is `off` or `nope`

src/design-system/components/text-field/index.tsx
This PR makes `TextField` have the `data-1p-ignore` attribute if the autocomplete is turned off.
N/A
positions
=> fix(TextField): disable autocomplete in 1Password

src/design-system/components/text-field/index.tsx
This PR exports `TURN_OFF_AUTOCOMPLETE_INPUT_PROPS` to allow reusing them with other components.
N/A
positions
=> chore(TextField): make turn-off-autocomplete-props reusable

src/design-system/components/text-field/index.tsx
Force-hide LastPass autocomplete when it's off because it doesn't always respect `data-lpignore`.
N/A
positions
=> fix(TextField): force-hide LastPass autocomplete

package.json, src/design-system/components/table/index.tsx, src/design-system/components/table/table.stories.tsx, yarn.lock
This PR improves table performance by adding virtual scrolling support to it.
https://github.com/Lightning-AI/lightning-ui/assets/4187729/3941733d-29cd-4206-8176-fbef063cb11e
It is required to specify height, width, row height, and column widths for the virtualized table. Can be used with `AutoSizer` to dynamically calculate these.
Manual validation via the storybook.
positions
=> feat(Table): add virtual scrolling

src/design-system/components/text-field/index.tsx, src/design-system/components/text-field/text-field.stories.tsx
* remove stepper arrows as default
* add prop to include them
* adjust styling accordingly
n/a
positions
=> remove stepper arrows from number field by default

src/design-system/components/dialog/Dialog.tsx
Update text selection colors in modals for dark mode.
Before:
After:
none
- [] I wrote new tests \[for a bug or new feature\]
positions
=> fix(ui): update dark mode selection colors

src/design-system/components/alert/index.tsx, src/design-system/components/table/index.tsx
Before:
After:
* update table headers to allow overflow in order to maintain popover/tooltip visibility
* update toast background to strictly enforce due to user-identified transparent background (https://puu.sh/JOOmw/ee8ba91a80.png)
n/a
positions
=> fix(ui): table header overflow, toast background

src/design-system/components/alert/alert.stories.tsx, src/design-system/theme/index.tsx
Fixes contrast issues with text hovers on dark mode toasts.
Before:
After:
* update global styles for toast text highlight
n/a
positions
=> fix(ui: dark mode toast highlight

src/design-system/components/tabs/index.tsx, src/design-system/components/tabs/tabs.stories.tsx
Light:
Dark:
* add `variant={"grouped"}` prop based on `<JointTabs>` component in UI
* add alternate styles for dark mode
* update margins & padding for button group appearance
n/a
positions
=> feat(ui): add grouped variant for tabs component

.github/workflows/publish-pkg.yml, README.md
automate updating UI version in lightning repo when new version is released
none
positions
=> ci: bump version after publishing new version via PR

src/design-system/style.css
It adds `inconsolata` explicitly to the font stack used in `style.css`; it doesn't appear to be imported in the grid repository and thus may not work under certain circumstances, such as being called in the `FontWrapper` component.
Once merged, it'd be ideal to test the import in the `FontWrapper` component, which in turn would allow us to switch from `Roboto Mono` in Studio terminals to `inconsolata`.
=> Added inconsolata explicitly

src/design-system/components/dialog/DialogTitle.tsx
Introduces a prop for developers to inject a `data-testid` into the DialogTitle.
This allows for more granular control in CI tests.
Usage in the `distributed-4-4xt4` test.
- [-] I wrote new tests \[for a bug or new feature\]
- [-] I added screenshots or screencasts featuring all UI & UX changes introduced by the PR
positions
=> Fix(ci): Adding data test id to DialogTitle

src/design-system/components/table/index.tsx
allows passing keys for table rows to prevent out of sync keys when the ordering of the row changes
positions
=> fix(ui): allow key as input for table rows

src/design-system/components/tabs/index.tsx
Fixes `Tabs` not updating to the `selectedTab` property
<div>
<a href="https://www.loom.com/share/b89dd51201b14ee39fbd01c98359c466">
</a>
</div>
- ~~I wrote new tests \[for a bug or new feature\]~~
=> fix(ui) Tabs: Fix broken `selectedTab` property

src/design-system/components/select/index.tsx, src/design-system/components/select/select.stories.tsx
N/A
Validated with a 100-item `Select` in a storybook (see screenshots above).
positions
=> fix(ui): Select dropdown shouldn't expand to the whole height when there are a lot of options

src/design-system/components/select/index.tsx, src/design-system/components/select/select.stories.tsx, src/design-system/components/text-field/index.tsx
Allows the Component library TextField to have a custom `endAdornment`.
This is required for the inputs below:
Demo of Implementation: https://www.loom.com/share/8ef6273533624800ae455ea49942b36c?sid=e59714fa-4123-4902-8514-7cf67163101a
You cannot both pass an end adornment and inherit the default "Loading" state of inputs that interact with API requests.
positions
=> Feat(ui): Allow custom end adornment in Text Field

src/design-system/components/button/index.tsx
Following #301, this treats an accidental color change for `color="grey"` buttons found in manual testing after the first PR merged
Covered in previous PR
- ~I added screenshots featuring related Figma designs and links to the corresponding Figma nodes~
positions
=> fix(ui): Disabled buttons in dark mode (2/2)

src/design-system/components/button/index.tsx
This PR removes the weird "opacity" style specified on the "grey" disabled button.
We may need to adjust the grey button colors further.
positions
=> fix(Button): disabled grey button should be readable in dark mode

src/design-system/components/button/button.stories.tsx, src/design-system/components/button/index.tsx
Follow up to the #303 that makes sure that change in #303 applies only the the great outlined button in the dark mode.
https://github.com/Lightning-AI/lightning-ui/assets/4187729/09b17212-ec5b-4087-b0e0-f6000058f104
N/A
positions
=> fix(Button): ensure the text-only grey button has the correct disabled state
