- src/design-system/components/tabs/index.tsx
This PR fixes tab style nits introduces in the previous tabs PR.
N/A
Make sure it looks nice.
positions
> fix(tabs): style nits

- src/design-system/components/tabs/index.tsx
> feat(Tabs): allow passing ReactNode as a title

- src/design-system/components/tabs/index.tsx
> feat(Tabs): allow passing icon

- src/design-system/style.css
Using the same import we are using on lightning.ai.
N/A
positions
> feat(font): import Plus Jakarta Sans

- src/design-system/components/alert/index.tsx
- src/design-system/components/breadcrumbs/index.tsx
- src/design-system/components/card/CardHeader.tsx
- src/design-system/components/dialog/DialogImageActions.tsx
- src/design-system/components/dialog/DialogTitle.tsx
- src/design-system/components/empty-state/index.tsx
- src/design-system/components/form-label/index.tsx
- src/design-system/components/stepper/Step.tsx
- src/design-system/components/table/index.tsx
- src/design-system/components/toggle-button-group/index.tsx
- src/design-system/style.css
- src/design-system/theme/typography.ts
- src/shared/components/AppOverview.tsx
Make `Plus Jakarta Sans` default font instead of UCity.
N/A
Manual validation via storybook
positions
> feat(font): switch from UCity to Plus Jakarta Sans

- src/design-system/components/alert/index.tsx
- src/design-system/components/banner/index.tsx
- src/design-system/components/button/index.tsx
- src/design-system/components/card/CardHeader.tsx
- src/design-system/components/checkbox/index.tsx
- src/design-system/components/dialog/DialogImageActions.tsx
- src/design-system/components/dialog/DialogTitle.tsx
- src/design-system/components/dropdown/index.tsx
- src/design-system/components/empty-state/index.tsx
- src/design-system/components/form-helper-text/index.tsx
- src/design-system/components/form-label/index.tsx
- src/design-system/components/form-status-text/index.tsx
- src/design-system/components/label/index.tsx
- src/design-system/components/radio/index.tsx
- src/design-system/components/select/index.tsx
- src/design-system/components/stepper/Step.tsx
- src/design-system/components/switch/index.tsx
- src/design-system/components/text-field/index.tsx
- src/design-system/theme/components/tooltip.ts
- src/index.css
- src/shared/components/AppDetails.tsx
- src/shared/components/AppOverview.tsx
> feat(font): switch Roboto to Jakarta

- src/design-system/components/snackbar-provider/index.tsx
> Persistent Toast Messages

- src/design-system/components/tabs/index.tsx
* update tab styles for consistency with new ui
* add pseudo elements and flip border (outlined variant) to box shadow to prevent layout shift
* remove indicator
* update padding/spacing to match user dashboard ui
Manual validation, viewable in Storybook
positions
> update tab styles for new ui

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- src/design-system/components/dialog/Dialog.tsx
- src/design-system/components/dialog/DialogActions.tsx
- src/design-system/components/dialog/DialogContent.tsx
- src/design-system/components/dialog/DialogTitle.tsx
- src/design-system/components/dialog/dialog.stories.tsx
> fix(ui): dialog title centering + dialog component props

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- src/design-system/components/text-field/index.tsx
- src/design-system/theme/palette.ts
- src/design-system/theme/paletteDark.ts
> WIP: dark theme

- src/design-system/components/alert/index.tsx
- src/design-system/components/banner/index.tsx
- src/design-system/components/breadcrumbs/index.tsx
- src/design-system/components/card/CardHeader.tsx
- src/design-system/components/checkbox/index.tsx
- src/design-system/components/dialog/DialogTitle.tsx
- src/design-system/components/empty-state/index.tsx
- src/design-system/components/label/index.tsx
- src/design-system/components/radio/index.tsx
- src/design-system/components/select/index.tsx
- src/design-system/components/stepper/Step.tsx
- src/design-system/components/table/TableRow.tsx
- src/design-system/components/table/index.tsx
- src/design-system/components/text-field/index.tsx
- src/design-system/components/toggle-button-group/index.tsx
- src/design-system/components/typography/index.tsx
- src/design-system/theme/components/tooltip.ts
- src/design-system/theme/palette.ts
- src/design-system/theme/paletteDark.ts
- src/index.css
- remove old fonts
- nice tooltips
> dark mode clean up 4/n

- src/design-system/components/button/button.stories.tsx
- src/design-system/components/button/index.tsx
* add missing hover state for default/gradient button
* add cursor-following button variant & associated styles
N/A
> feature(ui): add hover state for gradient button + cursor follow variant

- src/design-system/components/select/index.tsx
> fix crash when label is undefined in select component

- src/design-system/components/tooltip/index.tsx
Lengthens delay time of tooltip -> 700ms
None
positions
> fix(ui): lengthen delay of tooltip invocaiton

- src/design-system/components/select/index.tsx
Needed for https://github.com/gridai/grid/pull/10146.
Relevant docs: https://mui.com/material-ui/react-text-field/
- [in the linked PR] I added screenshots or screencasts featuring all UI & UX changes introduced by the PR
positions
> Pass through `defaultValue` to MUI's `TextField`

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- src/design-system/components/button/button.stories.tsx
- src/design-system/components/button/index.tsx
- src/design-system/components/form-helper-text/index.tsx
- src/design-system/components/form-label/index.tsx
- src/design-system/components/form-status-text/index.tsx
- src/design-system/components/text-field/index.tsx
- src/design-system/theme/index.tsx
* fixes dark mode form styles
* fixes dark mode button styles
* adds dark mode background toggle for Storybook
* shift button border radius style to 8px w/ prop for pill-style
n/a
- [] I wrote new tests \[for a bug or new feature\]
positions
> fix(ui): dark mode fixes

- src/design-system/components/table/TableRow.tsx
- src/design-system/components/table/TableRowContentShowHover.tsx
- src/design-system/components/table/index.tsx
> feat(table): add transition to TableRowContentShowOnHover

- src/design-system/components/select/index.tsx
- src/design-system/components/text-field/index.tsx
Before:
After:
* update backgrounds to increase contrast
* update border colors to increase contrast
* equalize select & text components to match on dark
N/A
N/A
- [] I wrote new tests \[for a bug or new feature\]
positions
> update text & select component backgrounds -> dark

- src/design-system/components/select/index.tsx
Before:
After:
Uses the consistent checkbox patterns for multiselect components.
n/a
n/a
positions
> fix(ui): adjust multiselect checkbox for consistency

- src/design-system/theme/components/index.ts
- src/design-system/theme/components/popover.ts
Remove overlay from popover element.
Before:
After:
n/a
positions
> remove popover overlay

- src/design-system/components/tabs/index.tsx
* switches default tab background color from hardcoded white to theme primary background
n/a
n/a
n/a
positions
> fix tabpanel background

- src/design-system/components/select/index.tsx
Changing the 'props.value' of the `<Select>` component after the first render would not update the internal `selectedValue` state. Adds a simple `useEffect()` to update `selectedValue` whenever `props.value` is changed.
None
None
positions
> Fix `<Select>` component to allow controlled value

- src/design-system/components/select/index.tsx
customized this text
so that instead of "items" we can use a different word
positions
> selector customized text

- src/design-system/components/table/index.tsx
This change fixes the horizontal alignment of the virtualized table row content.
N/A
positions
> fix(Table): virtualized table row alignment

- src/design-system/components/table/index.tsx
This PR allows rendering virtualized Table without the header or without data.
N/A
positions
> fix(virtualized Table): assert column count only if it's known

- src/design-system/theme/index.tsx
Fixes dark mode selection globally (outside DS components and `#root`).
n/a
positions
> fix(ui): global selection fixes

- .storybook/preview.js
- src/design-system/components/switch/index.tsx
* Update styling for switch
* Make `label` optional
* Allow more params for customization (used by Studio power icon)
* Make it easier to toggle between light and dark mode in `preview.js`
[Figma](https://www.figma.com/file/ThtnzU8vKOVa3ZZaNe5gWJ/DS%3A-Styles-and-Components?node-id=2575%3A93413&mode=dev)
positions
> Update Switch theme

- .github/CODEOWNERS
> Update CODEOWNERS for CI

- src/design-system/theme/index.tsx
Before:
After:
* update selection colors for dark mode tooltips
n/a
positions
> fix(ui): dark mode tooltip selections

- README.md
> update readme with releasing

- src/components/IFrameRoute.tsx
- src/components/LayoutView.spec.tsx
- src/components/LayoutView.tsx
- src/design-system/components/breadcrumbs/index.tsx
- src/design-system/components/table/index.tsx
- src/utils/state.spec.ts
- tsconfig.json
This PR reduces the developer error by introducing a stricter TS check, `noUncheckedIndexedAccess`.
N/A
Manual validation + existing autotests should pass.
positions
> chore: enable `noUncheckedIndexedAccess` rule

- README.md
based on changes in https://github.com/Lightning-AI/lightning/pull/18736 we would need to update only single place in lightning repo
positions
> update instruction for use UI in `lightning`

- src/design-system/components/form-label/index.tsx
- src/design-system/components/tabs/index.tsx
- src/design-system/components/text-field/index.tsx
- src/design-system/components/typography/index.tsx
Fix various React errors:
* `onClick={false}`
* `autocomplete` is not a valid prop
* `<div> cannot appear as a descendant of <p>`
* By changing <FormLabel> to 
* By allowing <Typography> to accept an `element` props)
positions
> Fix React errors

- .github/dependabot.yml
the team mentioned there is not valid
positions
> set Jirka as default reviewer for GHA

- src/design-system/components/button/index.tsx
Fixes disabled outlined buttons in dark mode
<div>
<a href="https://www.loom.com/share/7213c2b19b61457395f29b7cf0e02546">
</a>
</div>
**Change plan** button is impossible to see because its disabled and black in color.
Testing active and disabled states across all button variants in the product.
- ~~I wrote new tests \[for a bug or new feature\]~~
- ~~I added screenshots featuring related Figma designs and links to the corresponding Figma nodes~~
positions
> fix(ui): Disabled buttons in dark mode
